name: Build

on:
  push:
    branches:
    - master
    - renovate/*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set Environment Variables
      run: |-
        echo "::set-env name=DOTNET_CLI_TELEMETRY_OPTOUT::1"
        echo "::set-env name=DOTNET_NOLOGO::1"

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: |-
        dotnet build ./src/ConsoleApplication/ConsoleApplication.csproj